# Generated by Django 5.1.15 on 2026-09-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_company'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='regions.district'),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='regions.province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='regency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='regions.regency'),
        ),
    ]
