# Generated by Django 5.1.15 on 2026-09-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_district_customer_province_customer_regency'),
        ('regions', '0002_country_alter_district_code_alter_regency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='regions.village'),
        ),
    ]
