# Generated by Django 5.1.15 on 2026-09-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='provinsi',
        ),
    ]
