from django.db import migrations


class Migration(migrations.Migration):
    """Rapikan urutan kolom customers_customer: FK dan field baru sekarang
    ada di antara data inti (name..notes) dan created_at/updated_at.

    PostgreSQL tidak bisa me-reorder kolom lewat ALTER, jadi satu-satunya
    cara bersih: bangun ulang tabelnya sesuai urutan field model.
    """

    dependencies = [
        ("customers", "0007_customer_avatar"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # customer: tahan FK + data dulu, bangun ulang tabel, kembalikan
                """
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_agent_id_88fea847_fk_accounts_customuser_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_company_id_d9d820a0_fk_accounts_company_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_district_id_312024e4_fk_regions_district_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_province_id_2aaeaea8_fk_regions_province_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_regency_id_4dedaf28_fk_regions_regency_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_village_id_7e8ba6e6_fk_regions_village_id;
                """,
                """
                CREATE TABLE customers_customer_new (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name character varying(150) NOT NULL,
                    company_name character varying(200) NOT NULL,
                    email character varying(254) NOT NULL,
                    phone character varying(20) NOT NULL,
                    address text NOT NULL,
                    province_id bigint,
                    regency_id bigint,
                    district_id bigint,
                    village_id bigint,
                    status character varying(20) NOT NULL,
                    agent_id bigint,
                    notes text NOT NULL,
                    avatar character varying(100),
                    company_id bigint,
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL
                );
                """,
                """
                INSERT INTO customers_customer_new (
                    id, name, company_name, email, phone, address,
                    province_id, regency_id, district_id, village_id,
                    status, agent_id, notes, avatar, company_id,
                    created_at, updated_at
                )
                SELECT
                    id, name, company_name, email, phone, address,
                    province_id, regency_id, district_id, village_id,
                    status, agent_id, notes, avatar, company_id,
                    created_at, updated_at
                FROM customers_customer;
                """,
                "DROP TABLE customers_customer CASCADE;",
                "ALTER TABLE customers_customer_new RENAME TO customers_customer;",
                """
                CREATE INDEX customers_customer_agent_id_idx ON customers_customer (agent_id);
                CREATE INDEX customers_customer_company_id_idx ON customers_customer (company_id);
                CREATE INDEX customers_customer_district_id_idx ON customers_customer (district_id);
                CREATE INDEX customers_customer_province_id_idx ON customers_customer (province_id);
                CREATE INDEX customers_customer_regency_id_idx ON customers_customer (regency_id);
                CREATE INDEX customers_customer_village_id_idx ON customers_customer (village_id);
                """,
                """
                ALTER TABLE customers_customer
                    ADD CONSTRAINT customers_customer_agent_id_fk FOREIGN KEY (agent_id)
                        REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED,
                    ADD CONSTRAINT customers_customer_company_id_fk FOREIGN KEY (company_id)
                        REFERENCES accounts_company(id) DEFERRABLE INITIALLY DEFERRED,
                    ADD CONSTRAINT customers_customer_province_id_fk FOREIGN KEY (province_id)
                        REFERENCES regions_province(id) DEFERRABLE INITIALLY DEFERRED,
                    ADD CONSTRAINT customers_customer_regency_id_fk FOREIGN KEY (regency_id)
                        REFERENCES regions_regency(id) DEFERRABLE INITIALLY DEFERRED,
                    ADD CONSTRAINT customers_customer_district_id_fk FOREIGN KEY (district_id)
                        REFERENCES regions_district(id) DEFERRABLE INITIALLY DEFERRED,
                    ADD CONSTRAINT customers_customer_village_id_fk FOREIGN KEY (village_id)
                        REFERENCES regions_village(id) DEFERRABLE INITIALLY DEFERRED;
                """,
            ],
            reverse_sql=[
                # balik ke urutan lama (jarang dipakai; lengkap untuk konsistensi)
                "SELECT 1",
            ],
        ),
    ]
