# Generated by Django 5.1.15 on 2026-09-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_rapikan_urutan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
    ]
