from django.db import migrations


class Migration(migrations.Migration):
    """Tambah kolom country_id di posisi yang benar (sebelum province).

    PostgreSQL gak bisa nambah kolom di tengah, jadi sama kayak 0008:
    bangun ulang tabelnya biar urutannya rapi. Sekalian backfill
    country_id customer lama ke Indonesia (satu-satunya negara di DB).
    """

    dependencies = [
        ("customers", "0009_remove_customer_company"),
        ("regions", "0002_country_alter_district_code_alter_regency_code_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_agent_id_88fea847_fk_accounts_customuser_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_district_id_312024e4_fk_regions_district_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_province_id_2aaeaea8_fk_regions_province_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_regency_id_4dedaf28_fk_regions_regency_id;
                ALTER TABLE customers_customer DROP CONSTRAINT IF EXISTS customers_customer_village_id_7e8ba6e6_fk_regions_village_id;
                """,
                """
                CREATE TABLE customers_customer_new (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name character varying(150) NOT NULL,
                    company_name character varying(200) NOT NULL,
                    email character varying(254) NOT NULL,
                    phone character varying(20) NOT NULL,
                    address text NOT NULL,
                    country_id bigint,
                    province_id bigint,
                    regency_id bigint,
                    district_id bigint,
                    village_id bigint,
                    status character varying(20) NOT NULL,
                    agent_id bigint,
                    notes text NOT NULL,
                    avatar character varying(100),
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL
                );
                """,
                """
                INSERT INTO customers_customer_new (
                    id, name, company_name, email, phone, address,
                    country_id, province_id, regency_id, district_id, village_id,
                    status, agent_id, notes, avatar,
                    created_at, updated_at
                )
                SELECT
                    id, name, company_name, email, phone, address,
                    1, province_id, regency_id, district_id, village_id,
                    status, agent_id, notes, avatar,
                    created_at, updated_at
                FROM customers_customer;
                """,
                "DROP TABLE customers_customer CASCADE;",
                "ALTER TABLE customers_customer_new RENAME TO customers_customer;",
                """
                CREATE INDEX customers_customer_agent_id_idx ON customers_customer (agent_id);
                CREATE INDEX customers_customer_country_id_idx ON customers_customer (country_id);
                CREATE INDEX customers_customer_district_id_idx ON customers_customer (district_id);
                CREATE INDEX customers_customer_province_id_idx ON customers_customer (province_id);
                CREATE INDEX customers_customer_regency_id_idx ON customers_customer (regency_id);
                CREATE INDEX customers_customer_village_id_idx ON customers_customer (village_id);
                """,
                """
                ALTER TABLE customers_customer
                    ADD CONSTRAINT customers_customer_agent_id_88fea847_fk_accounts_customuser_id
                    FOREIGN KEY (agent_id) REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE customers_customer
                    ADD CONSTRAINT customers_customer_country_id_0342632b_fk_regions_country_id
                    FOREIGN KEY (country_id) REFERENCES regions_country(id) DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE customers_customer
                    ADD CONSTRAINT customers_customer_district_id_312024e4_fk_regions_district_id
                    FOREIGN KEY (district_id) REFERENCES regions_district(id) DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE customers_customer
                    ADD CONSTRAINT customers_customer_province_id_2aaeaea8_fk_regions_province_id
                    FOREIGN KEY (province_id) REFERENCES regions_province(id) DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE customers_customer
                    ADD CONSTRAINT customers_customer_regency_id_4dedaf28_fk_regions_regency_id
                    FOREIGN KEY (regency_id) REFERENCES regions_regency(id) DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE customers_customer
                    ADD CONSTRAINT customers_customer_village_id_7e8ba6e6_fk_regions_village_id
                    FOREIGN KEY (village_id) REFERENCES regions_village(id) DEFERRABLE INITIALLY DEFERRED;
                """,
            ],
            reverse_sql=[
                "ALTER TABLE customers_customer DROP COLUMN IF EXISTS country_id;",
            ],
        ),
    ]
