# Generated by Django 5.1.15 on 2026-09-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('kategori', models.CharField(choices=[('Aset', 'Aset'), ('Liabilitas', 'Liabilitas'), ('Ekuitas', 'Ekuitas'), ('Pendapatan', 'Pendapatan'), ('Beban', 'Beban')], max_length=30)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'COA',
                'verbose_name_plural': 'COA',
                'ordering': ['kode'],
            },
        ),
    ]
