# Generated by Django 5.1.15 on 2026-09-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_phone'),
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coa',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coa_entries', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='coa',
            name='kode',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='coa',
            constraint=models.UniqueConstraint(fields=('company', 'kode'), name='unique_coa_kode_per_company'),
        ),
    ]
