# Generated by Django 5.1.15 on 2026-09-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0002_coa_company_alter_coa_kode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coa',
            name='company',
        ),
    ]
