# Generated by Django 5.1.15 on 2026-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0003_remove_coa_company'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coa',
            constraint=models.UniqueConstraint(fields=('kode',), name='unique_coa_kode'),
        ),
    ]
